version: '3'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  client:
    build: ./client
    ports:
      - "4000:4000"
    environment:
      - CLIENT_PORT=4000
