version: '3'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_FILE=/app/data/data.db
    volumes:
      - ./data:/app/data
  client:
    build: ./client
    ports:
      - "4000:4000"
    environment:
      - CLIENT_PORT=4000
